window.deliveryStudioData = {
  "kpis": [
    {
      "label": "Weekly delivery orders modeled",
      "value": "45,945",
      "note": "synthetic operating baseline"
    },
    {
      "label": "Under-25-minute SLA",
      "value": "75.6%",
      "note": "weighted by orders"
    },
    {
      "label": "Order accuracy",
      "value": "96.5%",
      "note": "bag and make quality"
    },
    {
      "label": "Top monthly value",
      "value": "$41,338",
      "note": "Capacity-aware delivery promise"
    }
  ],
  "topSegment": {
    "segment_id": "SEG08",
    "segment_name": "Late-day promotion spike",
    "scenario": "Promotion",
    "channel": "Third-party marketplace",
    "owner": "Growth partnerships",
    "weekly_orders": 5974,
    "under_25_min_sla_pct": 59.6,
    "order_accuracy_pct": 95.5,
    "handoff_wait_minutes": 5.7,
    "capacity_utilization_pct": 93.1,
    "customer_contact_rate_pct": 2.07,
    "sentiment_score": 53.8,
    "estimated_weekly_drag_usd": 1910,
    "priority_score": 112.8,
    "decision": "Intervene"
  },
  "segments": [
    {
      "segment_id": "SEG08",
      "segment_name": "Late-day promotion spike",
      "scenario": "Promotion",
      "channel": "Third-party marketplace",
      "owner": "Growth partnerships",
      "weekly_orders": 5974,
      "under_25_min_sla_pct": 59.6,
      "order_accuracy_pct": 95.5,
      "handoff_wait_minutes": 5.7,
      "capacity_utilization_pct": 93.1,
      "customer_contact_rate_pct": 2.07,
      "sentiment_score": 53.8,
      "estimated_weekly_drag_usd": 1910,
      "priority_score": 112.8,
      "decision": "Intervene"
    },
    {
      "segment_id": "SEG10",
      "segment_name": "Airport and campus pickup zones",
      "scenario": "Travel hub",
      "channel": "Mixed digital",
      "owner": "Store operations",
      "weekly_orders": 2844,
      "under_25_min_sla_pct": 63.8,
      "order_accuracy_pct": 96.5,
      "handoff_wait_minutes": 5.5,
      "capacity_utilization_pct": 81.8,
      "customer_contact_rate_pct": 1.83,
      "sentiment_score": 56.7,
      "estimated_weekly_drag_usd": 728,
      "priority_score": 87.2,
      "decision": "Intervene"
    },
    {
      "segment_id": "SEG04",
      "segment_name": "Suburban drive-thru collision",
      "scenario": "Morning rush",
      "channel": "Mixed digital",
      "owner": "Store operations",
      "weekly_orders": 6725,
      "under_25_min_sla_pct": 71.4,
      "order_accuracy_pct": 96.1,
      "handoff_wait_minutes": 5.1,
      "capacity_utilization_pct": 90.6,
      "customer_contact_rate_pct": 1.62,
      "sentiment_score": 61.3,
      "estimated_weekly_drag_usd": 1588,
      "priority_score": 81.3,
      "decision": "Intervene"
    },
    {
      "segment_id": "SEG05",
      "segment_name": "Driver arrival before make-ready",
      "scenario": "All-day",
      "channel": "Third-party marketplace",
      "owner": "Delivery partnerships",
      "weekly_orders": 4090,
      "under_25_min_sla_pct": 76.9,
      "order_accuracy_pct": 96.9,
      "handoff_wait_minutes": 6.5,
      "capacity_utilization_pct": 71.9,
      "customer_contact_rate_pct": 1.33,
      "sentiment_score": 60.2,
      "estimated_weekly_drag_usd": 785,
      "priority_score": 64.4,
      "decision": "Intervene"
    },
    {
      "segment_id": "SEG06",
      "segment_name": "High-rise courier dwell",
      "scenario": "Urban core",
      "channel": "Third-party marketplace",
      "owner": "Delivery partnerships",
      "weekly_orders": 3146,
      "under_25_min_sla_pct": 68.6,
      "order_accuracy_pct": 97.4,
      "handoff_wait_minutes": 4.7,
      "capacity_utilization_pct": 68.6,
      "customer_contact_rate_pct": 1.57,
      "sentiment_score": 62.7,
      "estimated_weekly_drag_usd": 633,
      "priority_score": 63.7,
      "decision": "Intervene"
    },
    {
      "segment_id": "SEG03",
      "segment_name": "Food-heavy lunch bundles",
      "scenario": "Lunch",
      "channel": "Third-party marketplace",
      "owner": "Menu operations",
      "weekly_orders": 5236,
      "under_25_min_sla_pct": 71.0,
      "order_accuracy_pct": 96.0,
      "handoff_wait_minutes": 3.9,
      "capacity_utilization_pct": 75.4,
      "customer_contact_rate_pct": 1.63,
      "sentiment_score": 64.4,
      "estimated_weekly_drag_usd": 1259,
      "priority_score": 62.5,
      "decision": "Intervene"
    },
    {
      "segment_id": "SEG01",
      "segment_name": "Peak espresso rush delivery",
      "scenario": "Morning rush",
      "channel": "Third-party marketplace",
      "owner": "Store operations",
      "weekly_orders": 7230,
      "under_25_min_sla_pct": 78.6,
      "order_accuracy_pct": 96.8,
      "handoff_wait_minutes": 4.3,
      "capacity_utilization_pct": 88.1,
      "customer_contact_rate_pct": 1.28,
      "sentiment_score": 68.5,
      "estimated_weekly_drag_usd": 1339,
      "priority_score": 55.4,
      "decision": "Intervene"
    },
    {
      "segment_id": "SEG07",
      "segment_name": "Cold beverage customization",
      "scenario": "Afternoon",
      "channel": "Owned app delivery",
      "owner": "Digital product",
      "weekly_orders": 3744,
      "under_25_min_sla_pct": 93.4,
      "order_accuracy_pct": 94.8,
      "handoff_wait_minutes": 2.9,
      "capacity_utilization_pct": 71.0,
      "customer_contact_rate_pct": 0.98,
      "sentiment_score": 62.2,
      "estimated_weekly_drag_usd": 877,
      "priority_score": 29.2,
      "decision": "Monitor"
    },
    {
      "segment_id": "SEG02",
      "segment_name": "Owned-app delivery handoff",
      "scenario": "Morning rush",
      "channel": "Owned app delivery",
      "owner": "Digital product",
      "weekly_orders": 5046,
      "under_25_min_sla_pct": 88.6,
      "order_accuracy_pct": 97.6,
      "handoff_wait_minutes": 3.5,
      "capacity_utilization_pct": 81.4,
      "customer_contact_rate_pct": 0.84,
      "sentiment_score": 73.6,
      "estimated_weekly_drag_usd": 672,
      "priority_score": 20.8,
      "decision": "Monitor"
    },
    {
      "segment_id": "SEG09",
      "segment_name": "Low-volume cafe delivery",
      "scenario": "All-day",
      "channel": "Third-party marketplace",
      "owner": "Store operations",
      "weekly_orders": 1910,
      "under_25_min_sla_pct": 98.1,
      "order_accuracy_pct": 98.3,
      "handoff_wait_minutes": 2.4,
      "capacity_utilization_pct": 54.0,
      "customer_contact_rate_pct": 0.43,
      "sentiment_score": 82.1,
      "estimated_weekly_drag_usd": 185,
      "priority_score": 5.0,
      "decision": "Monitor"
    }
  ],
  "initiatives": [
    {
      "initiative_id": "OPP01",
      "title": "Capacity-aware delivery promise",
      "problem": "Delivery promises do not consistently reflect store load during peak or promotion windows.",
      "solution": "Throttle or shift quoted ready times when cafe, mobile, drive-thru, and delivery queues exceed capacity.",
      "target_segments": "SEG01, SEG04, SEG08",
      "weekly_orders_in_scope": 19929,
      "baseline_weekly_drag_usd": 4837,
      "expected_order_lift_pct": 2.8,
      "expected_refund_reduction_pct": 34,
      "labor_minutes_saved_weekly": 116,
      "confidence_pct": 78,
      "effort_points": 8,
      "partner_complexity": "Medium",
      "monthly_value_usd": 41338,
      "opportunity_score": 213.1,
      "rollout_recommendation": "Pilot in high-volume morning and promotion stores",
      "decision": "Ship pilot",
      "avg_segment_priority": 83.2
    },
    {
      "initiative_id": "OPP03",
      "title": "Food bundle readiness checklist",
      "problem": "Food-heavy delivery bundles increase missing-item contacts and remake work.",
      "solution": "Add a packaging confirmation step for food items and bag-level label checks.",
      "target_segments": "SEG03, SEG01",
      "weekly_orders_in_scope": 12466,
      "baseline_weekly_drag_usd": 2598,
      "expected_order_lift_pct": 1.2,
      "expected_refund_reduction_pct": 41,
      "labor_minutes_saved_weekly": 71,
      "confidence_pct": 82,
      "effort_points": 4,
      "partner_complexity": "Low",
      "monthly_value_usd": 13926,
      "opportunity_score": 94.7,
      "rollout_recommendation": "Launch as standard work in food-heavy cafes",
      "decision": "Ship pilot",
      "avg_segment_priority": 59.0
    },
    {
      "initiative_id": "OPP02",
      "title": "Driver-arrival pacing signal",
      "problem": "Couriers often arrive before the order is sealed, creating dwell time and counter congestion.",
      "solution": "Send partner platforms a make-ready signal that releases drivers closer to actual handoff time.",
      "target_segments": "SEG05, SEG06, SEG10",
      "weekly_orders_in_scope": 10080,
      "baseline_weekly_drag_usd": 2146,
      "expected_order_lift_pct": 1.8,
      "expected_refund_reduction_pct": 22,
      "labor_minutes_saved_weekly": 92,
      "confidence_pct": 74,
      "effort_points": 7,
      "partner_complexity": "High",
      "monthly_value_usd": 12624,
      "opportunity_score": 61.4,
      "rollout_recommendation": "Partner integration test with two courier platforms",
      "decision": "Ship pilot",
      "avg_segment_priority": 71.8
    },
    {
      "initiative_id": "OPP05",
      "title": "Partner exception weekly review",
      "problem": "Partner asks and escalations arrive faster than teams can separate urgent defects from noise.",
      "solution": "Create a weekly operating review that classifies exceptions by SLA, defect cost, and owner.",
      "target_segments": "SEG05, SEG08, SEG10",
      "weekly_orders_in_scope": 12908,
      "baseline_weekly_drag_usd": 3423,
      "expected_order_lift_pct": 0.7,
      "expected_refund_reduction_pct": 18,
      "labor_minutes_saved_weekly": 130,
      "confidence_pct": 86,
      "effort_points": 3,
      "partner_complexity": "Low",
      "monthly_value_usd": 8857,
      "opportunity_score": 60.4,
      "rollout_recommendation": "Standardize across product, operations, and partner management",
      "decision": "Ship pilot",
      "avg_segment_priority": 88.1
    },
    {
      "initiative_id": "OPP06",
      "title": "Delivery shelf zoning guide",
      "problem": "Physical handoff zones are inconsistent, especially where mobile pickup and delivery share space.",
      "solution": "Define shelf zones, courier pickup cues, and exception handling by store format.",
      "target_segments": "SEG04, SEG06, SEG10",
      "weekly_orders_in_scope": 12715,
      "baseline_weekly_drag_usd": 2949,
      "expected_order_lift_pct": 1.0,
      "expected_refund_reduction_pct": 17,
      "labor_minutes_saved_weekly": 83,
      "confidence_pct": 71,
      "effort_points": 5,
      "partner_complexity": "Medium",
      "monthly_value_usd": 9036,
      "opportunity_score": 55.7,
      "rollout_recommendation": "Store-format playbook with before and after measurement",
      "decision": "Ship pilot",
      "avg_segment_priority": 77.4
    },
    {
      "initiative_id": "OPP04",
      "title": "Customization risk guardrail",
      "problem": "Complex customized beverages have higher defect and negative feedback rates in delivery.",
      "solution": "Flag high-risk builds, simplify delivery-specific modifier defaults, and add packout verification.",
      "target_segments": "SEG07, SEG02",
      "weekly_orders_in_scope": 8790,
      "baseline_weekly_drag_usd": 1549,
      "expected_order_lift_pct": 1.5,
      "expected_refund_reduction_pct": 29,
      "labor_minutes_saved_weekly": 64,
      "confidence_pct": 69,
      "effort_points": 6,
      "partner_complexity": "Medium",
      "monthly_value_usd": 8868,
      "opportunity_score": 51.4,
      "rollout_recommendation": "A/B test on cold beverage delivery orders",
      "decision": "Discovery sprint",
      "avg_segment_priority": 25.0
    }
  ],
  "requirements": [
    {
      "req_id": "REQ01",
      "initiative_id": "OPP01",
      "requirement": "Calculate a live delivery promise adjustment from channel queue, labor capacity, and make-line load.",
      "acceptance": "Quoted delivery-ready time shifts when capacity utilization exceeds 88% for 15 minutes.",
      "metric": "Under-25-minute SLA",
      "owner": "Digital product"
    },
    {
      "req_id": "REQ02",
      "initiative_id": "OPP01",
      "requirement": "Expose a capacity reason code in the partner operations digest.",
      "acceptance": "Every adjusted promise includes a source reason and recovery owner.",
      "metric": "Escalations with owner",
      "owner": "Store operations"
    },
    {
      "req_id": "REQ03",
      "initiative_id": "OPP02",
      "requirement": "Publish make-ready event timing to delivery partners for eligible orders.",
      "acceptance": "Partner receives make-ready signal within 60 seconds of bag seal scan.",
      "metric": "Courier wait minutes",
      "owner": "Delivery partnerships"
    },
    {
      "req_id": "REQ04",
      "initiative_id": "OPP03",
      "requirement": "Add food item confirmation before delivery bag handoff.",
      "acceptance": "Bag cannot be marked ready until required food items are confirmed.",
      "metric": "Missing-item contact rate",
      "owner": "Menu operations"
    },
    {
      "req_id": "REQ05",
      "initiative_id": "OPP04",
      "requirement": "Flag high-risk customization combinations on delivery orders.",
      "acceptance": "The top 20 high-defect modifier combinations receive a packout alert.",
      "metric": "Order accuracy",
      "owner": "Digital product"
    },
    {
      "req_id": "REQ06",
      "initiative_id": "OPP05",
      "requirement": "Create a weekly partner exception packet with decision status.",
      "acceptance": "At least 95% of partner asks are classified as ship, test, defer, or monitor.",
      "metric": "Partner request aging",
      "owner": "Partner management"
    },
    {
      "req_id": "REQ07",
      "initiative_id": "OPP06",
      "requirement": "Attach store-format handoff instructions to each pilot store.",
      "acceptance": "Each pilot store has a documented shelf zone and courier pickup cue.",
      "metric": "Handoff wait minutes",
      "owner": "Store operations"
    }
  ],
  "feedback": [
    {
      "feedback_id": "FB01001",
      "segment_id": "SEG08",
      "category": "Promise accuracy",
      "theme": "Delivery arrived later than quoted",
      "weekly_mentions": 306,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB01002",
      "segment_id": "SEG08",
      "category": "Partner handoff",
      "theme": "Courier waited at counter",
      "weekly_mentions": 255,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB01003",
      "segment_id": "SEG08",
      "category": "Packaging accuracy",
      "theme": "Missing food item",
      "weekly_mentions": 253,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB01004",
      "segment_id": "SEG08",
      "category": "Make accuracy",
      "theme": "Drink customization missed",
      "weekly_mentions": 285,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB02005",
      "segment_id": "SEG10",
      "category": "Promise accuracy",
      "theme": "Delivery arrived later than quoted",
      "weekly_mentions": 191,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB02006",
      "segment_id": "SEG10",
      "category": "Partner handoff",
      "theme": "Courier waited at counter",
      "weekly_mentions": 229,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB02007",
      "segment_id": "SEG10",
      "category": "Packaging accuracy",
      "theme": "Missing food item",
      "weekly_mentions": 193,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB02008",
      "segment_id": "SEG10",
      "category": "Make accuracy",
      "theme": "Drink customization missed",
      "weekly_mentions": 188,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB03009",
      "segment_id": "SEG04",
      "category": "Promise accuracy",
      "theme": "Delivery arrived later than quoted",
      "weekly_mentions": 188,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    },
    {
      "feedback_id": "FB03010",
      "segment_id": "SEG04",
      "category": "Partner handoff",
      "theme": "Courier waited at counter",
      "weekly_mentions": 232,
      "severity": "High",
      "product_question": "Should we change the promise, handoff, packaging, or requirement before scaling?"
    }
  ],
  "partnerPlan": [
    {
      "initiative_id": "OPP01",
      "title": "Capacity-aware delivery promise",
      "partner_touchpoint": "Weekly launch review",
      "ops_owner": "Delivery partnerships",
      "decision_packet": "Ship pilot with 78% confidence",
      "escalation_rule": "SLA miss above 8% or partner cancel rate above 1.5%",
      "next_review": "2026-04-17"
    },
    {
      "initiative_id": "OPP03",
      "title": "Food bundle readiness checklist",
      "partner_touchpoint": "Weekly launch review",
      "ops_owner": "Delivery partnerships",
      "decision_packet": "Ship pilot with 82% confidence",
      "escalation_rule": "SLA miss above 8% or partner cancel rate above 1.5%",
      "next_review": "2026-04-17"
    },
    {
      "initiative_id": "OPP02",
      "title": "Driver-arrival pacing signal",
      "partner_touchpoint": "Weekly launch review",
      "ops_owner": "Store operations",
      "decision_packet": "Ship pilot with 74% confidence",
      "escalation_rule": "SLA miss above 8% or partner cancel rate above 1.5%",
      "next_review": "2026-04-17"
    },
    {
      "initiative_id": "OPP05",
      "title": "Partner exception weekly review",
      "partner_touchpoint": "Weekly launch review",
      "ops_owner": "Delivery partnerships",
      "decision_packet": "Ship pilot with 86% confidence",
      "escalation_rule": "SLA miss above 8% or partner cancel rate above 1.5%",
      "next_review": "2026-04-17"
    },
    {
      "initiative_id": "OPP06",
      "title": "Delivery shelf zoning guide",
      "partner_touchpoint": "Weekly launch review",
      "ops_owner": "Delivery partnerships",
      "decision_packet": "Ship pilot with 71% confidence",
      "escalation_rule": "SLA miss above 8% or partner cancel rate above 1.5%",
      "next_review": "2026-04-17"
    },
    {
      "initiative_id": "OPP04",
      "title": "Customization risk guardrail",
      "partner_touchpoint": "Two-week discovery review",
      "ops_owner": "Delivery partnerships",
      "decision_packet": "Discovery sprint with 69% confidence",
      "escalation_rule": "Unowned requirement, unclear metric, or partner dependency blocked",
      "next_review": "2026-04-17"
    }
  ]
};
